Repository gunnarmorling/1brc, pull requests merged in 2024-01, with the labels that each got.

#22 Add CalculateAverage_ebarlas submission.
  calculate_average_ebarlas.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_ebarlas.java
Labels: license-header-missing

#56 Updates to CalculateAverage_spullara
  calculate_average_spullara.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_spullara.java
Labels: test failure

#85 Use proper hash key collision detection scheme.
  calculate_average_ebarlas.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_ebarlas.java
Labels: test failure

#71 Add CalculateAverage_moysesb
  calculate_average_moysesb.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_moysesb.java
Labels: output differs

#68 Trying to fix the endian issue
  calculate_average_royvanrijn.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_royvanrijn.java
Labels: test failure

#54 profiler driven approach
  calculate_average_nstng.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_nstng.java
Labels: test failure

#47 initial deemkeen
  calculate_average_deemkeen.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_deemkeen.java
Labels: test failure

#60 Update seijikun implementation
  calculate_average_seijikun.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_seijikun.java
Labels: test failure

#3 Algorithmic Tweaks, parallel stream, memory mapped file
  calculate_average_twobiers.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_twobiers.java
Labels: test failure

#64 Adding Johannes Schüth's submission
  calculate_average_jotschi.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_jotschi.java
Labels: test failure

#27 artpar's attempt
  calculate_average_artpar.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_artpar.java
Labels: test failure

#73 A solution with Actor Model concurrency and MappedByteBuffer
  calculate_average_yavuztas.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_yavuztas.java
Labels: test failure

#53 Implementation of 1brc - felix19350
  calculate_average_felix19350.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_felix19350.java
Labels: test failure

#59 hchiorean - Initial version
  calculate_average_hchiorean.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_hchiorean.java
Labels: test failure

#41 Mudit/initial attempt
  calculate_average_mudit-saxena.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_muditsaxena.java
Labels: test failure

#75 Submitting my version
  calculate_average_obourgain.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_obourgain.java
Labels: test failure

#176 Improved artsiomkorzun solution
  calculate_average_artsiomkorzun.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_artsiomkorzun.java
Labels: test failure

#240 Simple, slow but very short. :-)
  calculate_average_alesj.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_alesj.java
Labels: test failure

#193 First version - roman_r_m
  calculate_average_roman-r-m.sh
  prepare_roman-r-m.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_roman_r_m.java
Labels: test failure

#292 First Version
  calculate_average_SamuelYvon.sh
  prepare_SamuelYvon.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_samuelyvon.java
Labels: test failure

#153 Submission @jbachorik
  calculate_average_jbachorik.sh
  prepare_jbachorik.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_jbachorik.java
Labels: test failure

#200 artpar 2nd attempt
  calculate_average_artpar.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_artpar.java
Labels: test failure

#332 Graal Native for SamuelYvon
  calculate_average_SamuelYvon.sh
  prepare_SamuelYvon.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_SamuelYvon.java
Labels: test failure

#269 1brc submission - thanhtrinity
  calculate_average_thanhtrinity.sh
  prepare_thanhtrinity.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_thanhtrinity.java
Labels: output differs

#310 Updates to Andrew Sun's entry
  calculate_average_asun.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_asun.java
Labels: needs rebase

#226 first attempt
  calculate_average_maximz101.sh
  prepare_maximz101.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_maximz101.java
Labels: output differs

#222 First version of implementation - omarchenko4j
  calculate_average_omarchenko4j.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_omarchenko4j.java
Labels: test failure

#294 submission for kidlike
  calculate_average_Kidlike.sh
  prepare_Kidlike.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_Kidlike.java
Labels: test failure

#394 Add implementation for user unbounded
  calculate_average_unbounded.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_unbounded.java
Labels: test failure

#219 Initial 1brc version by plbpietrz
  calculate_average_plbpietrz.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_plbpietrz.java
Labels: test failure

#427 Read file in multiple threads and String to Text
  calculate_average_japplis.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_japplis.java
Labels: test failure

#438 MahmoudFawzyKhalil's implementation
  calculate_average_MahmoudFawzyKhalil.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_MahmoudFawzyKhalil.java
Labels: test failure

#433 jparera's initial implementation
  calculate_average_jparera.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_jparera.java
Labels: output differs

#460 GitHub Copilot Chat with the help of agoncal
  calculate_average_agoncal.sh
  prepare_agoncal.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_agoncal.java
Labels: test failure

#525 Reduce allocations and heap size
  calculate_average_roman-r-m.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_roman_r_m.java
Labels: Fails 10K

#523 Small optimization for ebarlas submission.
  src/main/java/dev/morling/onebrc/CalculateAverage_ebarlas.java
Labels: test failure

#539 First optimal solution attempt
  calculate_average_gauravdeshmukh.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_gauravdeshmukh.java
Labels: Potential hash collisions

#524 Deploy v2 for parkertimmins
  src/main/java/dev/morling/onebrc/CalculateAverage_parkertimmins.java
Labels: output differs, Fails 10K

#526 fine tuning performance further
  calculate_average_karthikeyan97.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_karthikeyan97.java
Labels: test failure

#431 Laake Scates-Gervasi first submission (justplainlaake) [2.5s execution, locally similar time to top 5]
  calculate_average_justplainlaake.sh
  prepare_justplainlaake.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_justplainlaake.java
Labels: test failure

#558 Fix hundredwatt's entry on 10k dataset
  src/main/java/dev/morling/onebrc/CalculateAverage_hundredwatt.java
Labels: output differs

#600 (new submission) melgenek: ~top 15 on 10k. Buffered IO, VarHandles, vectors, custom hashtable
  calculate_average_melgenek.sh
  prepare_melgenek.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_melgenek.java
Labels: output differs

#553 serkan-ozal: Initial impl
  calculate_average_serkan-ozal.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_serkan_ozal.java
Labels: output differs

#515 CalculateAverage_pdrakatos
  calculate_average_PanagiotisDrakatos.sh
  prepare_PanagiotisDrakatos.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_PanagiotisDrakatos.java
Labels: output differs

#586 Initial submission for jonathan_aotearoa.
  calculate_average_jonathan-aotearoa.sh
  prepare_jonathan-aotearoa.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_jonathanaotearoa.java
Labels: Fails 10K

#602 Solution without unsafe using vector API
  calculate_average_giovannicuccu.sh
  github_users.txt
  prepare_giovannicuccu.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_giovannicuccu.java
  src/main/java/dev/morling/onebrc/CreateMeasurements3.java
Labels: Fails 10K

#550 improve speed, thanks to the following improvements:
  calculate_average_yavuztas.sh
  prepare_yavuztas.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_yavuztas.java
Labels: output differs, Fails 10K

#635 Attempt to fix segfault CalculateAverage_zerninv.java
  calculate_average_zerninv.sh
  prepare_zerninv.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_zerninv.java
Labels: output differs

#655 melgenek: minor improvements
  calculate_average_melgenek.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_melgenek.java
Labels: Fails 10K

#636 Gamlerhart Last Update: Disabling GC
  calculate_average_gamlerhart.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_gamlerhart.java
Labels: Fails 10K

#575 Adding solution for cb0s
  calculate_average_cb0s.sh
  prepare_cb0s.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_cb0s.java
Labels: test failure

#598 sudhirtumati implementation
  calculate_average_sudhirtumati.sh
  prepare_sudhirtumati.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_sudhirtumati.java
Labels: output differs

#510 Second attempt with various improvements
  calculate_average_JamalMulla.sh
  prepare_JamalMulla.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_JamalMulla.java
Labels: Fails 10K

#658 1brc submission by godofwharf
  calculate_average_godofwharf.sh
  prepare_godofwharf.sh
  src/main/java/dev/morling/onebrc/CalculateAverage_godofwharf.java
Labels: Potential hash collisions
